### ISSUE TITLE
Carga Masiva, último desarrollo

### ISSUE THREAD

**Issue by PaulMhurdock** [cfoch/SIGAD-business#34]
Se mejora corrige bugs en carga de permisos y perfil x permiso
Se retorna un reporte final para que se muestre en la pantalla de carga masiva una vez finalizado el proceso.
Cargas Masivas que se tienen a la fecha:
Categoria de Productos
Perfiles
Usuarios
Proveedores
Insumos
Tiendas
Tipo de Movimientos
Permisos
Fragilidad de Producto
Perfil x Permiso
Productos
Tipos de Pago
Producto x Insumo

**Comment by cfoch** [comment]
@Bryaam  por favor, completa la interfaz del reporte para aceptar el pull request.
